-- Einmal im Supabase SQL Editor ausführen. Der Secret-Key bzw. die Service-Role gehört nur in Vercel, niemals in den Browser.
create table if not exists public.kalki_price_observations (
  id bigint generated by default as identity primary key,
  provider text not null,
  external_id text not null,
  motorcycle_key text not null,
  part_template_id integer not null,
  title text not null,
  url text not null,
  price numeric not null,
  shipping_price numeric not null default 0,
  currency text not null default 'EUR',
  condition text,
  image_url text,
  query text,
  observed_at timestamptz not null default now(),
  is_active boolean not null default true,
  unique(provider, external_id, motorcycle_key, part_template_id)
);

create table if not exists public.kalki_price_cache (
  motorcycle_key text not null,
  part_template_id integer not null,
  min_price integer not null,
  realistic_price integer not null,
  max_price integer not null,
  observation_count integer not null default 0,
  confidence integer not null default 0,
  updated_at timestamptz not null default now(),
  primary key(motorcycle_key, part_template_id)
);

alter table public.kalki_price_observations enable row level security;
alter table public.kalki_price_cache enable row level security;
-- Keine öffentlichen Policies: KALKI greift serverseitig mit der Service Role zu.

create table if not exists public.kalki_market_checks (
  motorcycle_key text not null,
  part_template_id integer not null,
  provider text not null default 'ebay',
  status text not null,
  result_count integer not null default 0,
  query text,
  error_message text,
  checked_at timestamptz not null default now(),
  primary key(motorcycle_key, part_template_id, provider)
);

alter table public.kalki_market_checks enable row level security;
